### ISSUE TITLE
When I run the script, I get a syntax error in line 40, to do with vosk_link

### ISSUE THREAD

**Issue by theClubHopper** [patrickenfuego/Chapterize-Audiobooks#3]
Installed on my Windows 10 machine, with python3 and ffmpeg etc up to date. When I run any command involving chapterize_ab.py (including "-h"), I get the following error:

`File "C:\dev\chapterize-audiobooks-main\chapterize_ab.py", line 40
    vosk_link = f"[link={vosk_url}]this link[/link]"
                                                   ^
SyntaxError: invalid syntax`

Any ideas why?

**Comment by theClubHopper** [comment]
It took me a while to figure out what I was doing wrong - the reported error was a result of me accidentally omitting the required 'python' command beginning my line of Powershell input. Stupid mistake!

I also discovered that in Powershell, one can't natively run a script from the directory that the script is in. Seems counter intuitive to me but that's the way it is. So, I finally got 'python .\Chapterize-audiobooks-main\chapterize_ab.py -h' to work, but then the script soon stopped with multiple errors --at the vosk model download/check part of the process.

The 'en-us' 'small' model was already installed, and reinstalling everything from scratch did not help. I rechecked my PATH environment settings, good. And yes, I'd seen your message at 'permission denied' at the bottom of the instructions page here, and although I was getting the same message, this was not the same reason.  After many hours of experimentation, I found that that because I was not calling the script from within the 'Chapterize-audiobooks-main' folder, when it got to the vosk part, it expected to find the 'model' folder in a subdirectory of my current directory. 

The solution was to navigate to the Chapterize-audiobooks-main directory in Powershell and execute the following command:
`Set-Location .\Chapterize-Audiobooks-main\`

After this, I was able to run the command: "chapterize_ab.py 'D:\Audiobooks\MyAudioBook.mp3' and it ran, and completed, successfully.

Only issue now is that it picked up a false chapter break that I need to manually fix. But I'm impressed!

**Comment by patrickenfuego** [comment]
Hey there @theClubHopper! So sorry for the late response, my github notifications are inundated with security advisories for one of my old private website repositories lol.

I'm happy to hear you figured it out, AND you found a **new excluded phrase**! Awesome! That's exactly the type of feedback I want to get. 

I also really like your idea of generating a cue file - I'll get working on that and should have it out soon (as time permits).

As for the script directory, yes that is a limitation unfortunately - unless the `models` directory is added to system PATH (which I thought about doing), the OS isn't context aware in that case. So it's best to run it from the local directory to reduce any path resolution errors (should be the same for `defaults.toml` too, if you use that). 

Keep using it and let me know if you find any more phrases, or come up with some new ideas 😄

**Comment by patrickenfuego** [comment]
As an aside, you can fix that PowerShell issue by running the following command as an administrator:

```powershell
Set-ExecutionPolicy remoteSigned
```

**Comment by theClubHopper** [comment]
Cool. Thanks for that!
________________________________

**Comment by theClubHopper** [comment]
re: preamble and keywords – In that particular audiobook I was splitting, the preamble had no real identifiable keywords – even the dedication and epigraph were unannounced. So out of curiosity, I checked some other audiobooks I have and found that of the ones introducing the first chapter using the words “Chapter One” (rather than just “One” like so many unfortunately do), one book’s preamble was followed by an announced “Introduction” consisting of multiple read pages prior to the announcement of “Chapter One”. So that would be a good keyword to split on.

By the way, the only other suggestion I have is that numbers (track & chapter) are perhaps better written in 2-digit– format ie “01” vs “1” and so on. Windows natively sorts things properly but I was surprised to find that not every utility or app I threw my mp3s into sorted them properly, resulting in ‘1,10,11” and “19,2,20” etc.

**Comment by patrickenfuego** [comment]
@theClubHopper 

> By the way, the only other suggestion I have is that numbers (track & chapter) are perhaps better written in 2-digit– format ie “01” vs “1”

Interesting you bring that up, originally, I had used 2-digit numbers. I shall reimplement them 😃 

You make a good point about some books excluding "Chapter" and instead just announcing the numerical identifier. I'll have to think of a way around that without raising false positives 🤔
